/** @type {import('tailwindcss').Config} */

// Tailwind 只消费 apps/web/src/styles/tokens.css 的语义 Token；
// 颜色、几何、z-index 的取值以 tokens.css 为唯一真相源，这里不做任何数值决策。
// legacy 段为旧视觉体系的过渡映射，仅服务既有调用方，Task 13 统一清理。
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // 基础色彩（C 端总规范 §2.1）
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        ink: 'var(--ink)',
        muted: 'var(--muted)',
        line: 'var(--line)',
        stroke: 'var(--stroke)',
        action: 'var(--action)',
        'action-fg': 'var(--action-fg)',
        select: 'var(--select)',
        'select-fg': 'var(--select-fg)',
        date: 'var(--date)',
        tag: 'var(--tag)',
        focus: 'var(--focus)',
        danger: 'var(--danger)',
        'danger-fg': 'var(--danger-fg)',
        // 链身份四色点
        'dot-pink': 'var(--dot-pink)',
        'dot-blue': 'var(--dot-blue)',
        'dot-mint': 'var(--dot-mint)',
        'dot-purple': 'var(--dot-purple)',
        // Field（Field 规范 §4.1）
        'field-bg': 'var(--field-bg)',
        'field-bg-hover': 'var(--field-bg-hover)',
        'field-bg-disabled': 'var(--field-bg-disabled)',
        'field-placeholder': 'var(--field-placeholder)',
        'field-focus': 'var(--field-focus)',
        'field-danger': 'var(--field-danger)',
        // Overlay / Floating（Modal §6、Menu §5.1 / §9）
        scrim: 'var(--scrim)',
        'scrim-nested': 'var(--scrim-nested)',
        'floating-bg': 'var(--floating-bg)',
        'floating-hover': 'var(--floating-hover)',
        'floating-pressed': 'var(--floating-pressed)',
        'floating-danger-soft': 'var(--floating-danger-soft)',
        'floating-edge': 'var(--floating-edge)',
        'tooltip-bg': 'var(--tooltip-bg)',
        'tooltip-fg': 'var(--tooltip-fg)',
        // Feedback（Feedback 规范 §3.2）
        'feedback-error-bg': 'var(--feedback-error-bg)',
        'feedback-warning-bg': 'var(--feedback-warning-bg)',
        'feedback-info-bg': 'var(--feedback-info-bg)',
        'feedback-skeleton': 'var(--feedback-skeleton)',
        'feedback-toast-bg': 'var(--feedback-toast-bg)',
        // legacy 过渡映射（Task 13 清理）
        today: 'var(--today)',
        'knot-yesterday': 'var(--knot-yesterday)',
        'knot-older': 'var(--knot-older)',
        'dot-gold': 'var(--dot-gold)',
        'sticker-pink': 'var(--sticker-pink)',
        'sticker-blue': 'var(--sticker-blue)',
        'sticker-mint': 'var(--sticker-mint)',
        'sticker-purple': 'var(--sticker-purple)',
        'sticker-pink-line': 'var(--sticker-pink-line)',
        'sticker-blue-line': 'var(--sticker-blue-line)',
        'sticker-mint-line': 'var(--sticker-mint-line)',
        'sticker-purple-line': 'var(--sticker-purple-line)',
      },
      // 语义字号角色（C 端总规范 §2.2）：禁止页面扩散 text-[13px] 等私有尺度
      fontSize: {
        'page-title': ['24px', '32px'],
        'day-title': ['28px', '31px'],
        body: ['16px', '26px'],
        meta: ['13px', '20px'],
        caption: ['12px', '18px'],
      },
      boxShadow: {
        overlay: 'var(--overlay-shadow)',
        floating: 'var(--floating-shadow)',
        'action-sheet': 'var(--action-sheet-shadow)',
        toast: 'var(--feedback-toast-shadow)',
        // legacy 过渡映射（Task 13 清理）
        card: 'var(--elev)',
        sticker: 'var(--elev-sm)',
        fab: '0 12px 28px color-mix(in srgb, var(--action) 35%, transparent)',
      },
      zIndex: {
        floating: 'var(--z-floating)',
        overlay: 'var(--z-overlay)',
        'overlay-popover': 'var(--z-overlay-popover)',
        'overlay-floating': 'var(--z-overlay-floating)',
        tooltip: 'var(--z-tooltip)',
        toast: 'var(--z-toast)',
        'overlay-nested': 'var(--z-overlay-nested)',
        lightbox: 'var(--z-lightbox)',
      },
      borderRadius: {
        // 内容色面圆角（C 端总规范 §2.3：14–20px）；不覆盖默认 md/lg，避免影响未迁移页面
        'surface-md': 'var(--radius-md)',
        'surface-lg': 'var(--radius-lg)',
        button: 'var(--button-radius)',
        field: 'var(--field-radius)',
        overlay: 'var(--overlay-radius)',
        'sheet-mobile': 'var(--sheet-mobile-radius)',
        menu: 'var(--menu-radius)',
        'menu-item': 'var(--menu-item-radius)',
        'action-sheet': 'var(--action-sheet-radius)',
        'action-sheet-item': 'var(--action-sheet-item-radius)',
        tooltip: 'var(--tooltip-radius)',
        banner: 'var(--banner-radius)',
        toast: 'var(--toast-radius)',
        'inline-progress': 'var(--inline-progress-radius)',
        // legacy 过渡映射（Task 13 清理）
        card: 'var(--radius-lg)',
        sticker: '99px',
      },
      ringWidth: {
        focus: 'var(--focus-ring-w)',
        field: 'var(--field-ring-w)',
      },
      ringOffsetWidth: {
        focus: 'var(--focus-ring-offset)',
      },
      scale: {
        'button-pressed': 'var(--button-pressed-scale)',
      },
      opacity: {
        'button-disabled': 'var(--button-disabled-opacity)',
      },
      maxWidth: {
        content: 'var(--content)',
        dialog: 'var(--dialog-w)',
        'alert-dialog': 'var(--alert-dialog-w)',
        sheet: 'var(--sheet-w)',
        menu: 'var(--menu-max-w)',
        toast: 'var(--toast-max-w)',
        empty: 'var(--empty-max-w)',
      },
      minWidth: {
        menu: 'var(--menu-min-w)',
      },
      width: {
        sidebar: 'var(--sidebar)',
        rail: 'var(--rail)',
        'icon-button': 'var(--icon-button-size)',
        'menu-icon': 'var(--menu-icon-size)',
        'field-icon': 'var(--field-icon-size)',
        'field-end-visual': 'var(--field-end-visual)',
        'banner-icon': 'var(--banner-icon-size)',
        'inline-progress-spinner': 'var(--inline-progress-spinner)',
      },
      height: {
        control: 'var(--control-h)',
        'control-prominent': 'var(--control-h-prominent)',
        fab: 'var(--control-h-fab)',
        field: 'var(--field-h)',
        'icon-button': 'var(--icon-button-size)',
        'menu-item': 'var(--menu-item-h)',
        'action-sheet-item': 'var(--action-sheet-item-h)',
        'menu-icon': 'var(--menu-icon-size)',
        'field-icon': 'var(--field-icon-size)',
        'field-end-visual': 'var(--field-end-visual)',
        'banner-icon': 'var(--banner-icon-size)',
        'inline-progress-spinner': 'var(--inline-progress-spinner)',
        'inline-progress-track': 'var(--inline-progress-track-h)',
        // legacy 过渡映射（Task 13 清理）
        'control-sm': 'var(--control-h-sm)',
      },
      minHeight: {
        textarea: 'var(--textarea-min-h)',
        toast: 'var(--toast-min-h)',
        'inline-progress': 'var(--inline-progress-min-h)',
        'touch-control': 'var(--touch-control-min)',
        'field-end-hit': 'var(--field-end-hit)',
      },
      padding: {
        button: 'var(--button-px)',
        'button-pill': 'var(--button-pill-px)',
        field: 'var(--field-px)',
        overlay: 'var(--overlay-padding)',
        'overlay-mobile': 'var(--overlay-padding-mobile)',
        menu: 'var(--menu-padding)',
        'menu-item': 'var(--menu-item-px)',
        'action-sheet': 'var(--action-sheet-padding)',
        'tooltip-x': 'var(--tooltip-px)',
        'tooltip-y': 'var(--tooltip-py)',
        'banner-x': 'var(--banner-px)',
        'banner-y': 'var(--banner-py)',
        toast: 'var(--toast-px)',
        'empty-page': 'var(--empty-page-py)',
        'empty-page-mobile': 'var(--empty-page-py-mobile)',
        'empty-section': 'var(--empty-section-py)',
        // legacy 过渡映射（Task 13 清理）
        sidebar: 'var(--space-3)',
      },
      gap: {
        'button-icon': 'var(--button-icon-gap)',
        'field-label': 'var(--field-label-gap)',
        'field-support': 'var(--field-support-gap)',
        'field-stack': 'var(--field-stack-gap)',
        'field-stack-compact': 'var(--field-stack-compact)',
        'overlay-action': 'var(--overlay-action-gap)',
        'menu-icon': 'var(--menu-icon-gap)',
        'action-sheet-cancel': 'var(--action-sheet-cancel-gap)',
        banner: 'var(--banner-gap)',
        toast: 'var(--toast-gap)',
        'empty-action': 'var(--empty-action-gap)',
      },
      spacing: {
        // 供 inset / translate 等定位场景消费
        'menu-offset': 'var(--menu-offset)',
        'menu-viewport': 'var(--menu-viewport-gap)',
        'overlay-gap': 'var(--overlay-gap)',
        'sheet-mobile-top': 'var(--sheet-mobile-top-gap)',
      },
      inset: {
        sidebar: 'var(--sidebar)',
        rail: 'var(--rail)',
      },
    },
  },
  plugins: [],
};
