services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: moment_root_dev
      MYSQL_DATABASE: moment_dev
      MYSQL_USER: moment
      MYSQL_PASSWORD: moment_dev
    ports:
      - '3306:3306'
    volumes:
      - moment-mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-umoment', '-pmoment_dev']
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  moment-mysql: {}
