packages:
  - apps/*
  - packages/*
  - config/*

onlyBuiltDependencies:
  - bcrypt
  - esbuild

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc

ignoredOptionalDependencies:
  - openai
  - '@huggingface/transformers'
